### ISSUE TITLE
Doesn't compile with xcode 6.3.2

### ISSUE THREAD

**Issue by InderKumarRathore** [GitGarage/BLEMingleiOS#1]
I guess you're using swift 1.0 ?

**Comment by gitgarage** [comment]
This could well be the problem. I was barely able to run the lowest level required for AppCode due to the fact that I am writing the whole thing through a Maverics VM on my PC. I have just purchased a Mac with Yosemite so I should be able to resolve this issue soon.

**Comment by gitgarage** [comment]
I have updated the iOS version to support the newest version of Swift.

**Comment by InderKumarRathore** [comment]
Thank, I'll check that.
