### ISSUE TITLE
Crash when discovering Devices

### ISSUE THREAD

**Issue by eridbardhaj** [GitGarage/BLEMingleiOS#4]
Under didDiscoverPeripheral: 
`let datas = hexString.dataFromHexadecimalString()` app crashes because datas var is always nil. The case is connection between 2 iOS Devices (iPhone 5 and 6) using this app, but it seems I am not able to send data. Can you give me a hint or something regarding to this library, does this support connection between 2 iOS Devices?

**Comment by gitgarage** [comment]
It should be possible, although this library was designed primarily for cross-device (iOS <-> Android) with some changes it could easily support communication within one platform. Let me see what I can do...

**Comment by Mohd-Aamir-M** [comment]
Is there any update for Android to Android and iOS to iOS?
