### ISSUE TITLE
Analyzing dependencies failed

### ISSUE THREAD

**Issue by ghost** [GitGarage/BLEMingleiOS#5]
Re-creating CocoaPods due to major version update.
Analyzing dependencies
[!] The dependency `YapDatabase (~> 2.5)` is not used in any concrete target.
The dependency `PureLayout (~> 2.0)` is not used in any concrete target.
The dependency `Mantle (~> 1.4)` is not used in any concrete target.
The dependency `InAppSettingsKit (~> 2.2)` is not used in any concrete target.
The dependency `JSQMessagesViewController (~> 6.0)` is not used in any concrete target.
The dependency `IGIdenticon (~> 0.2.0)` is not used in any concrete target.
The dependency `libsodium (from`Podspecs/libsodium.podspec.json`)` is not used in any concrete target.

**Comment by gitgarage** [comment]
OK I am going to figure out what is going on here. What IDE are you using? It should work in Xcode but for ideal results you might try AppCode by JetBrains as that is what I developed it in. I am going to get this working again and test it on my new iPhone and Android.
