### ISSUE TITLE
Does not compile for Swift3

### ISSUE THREAD

**Issue by will-lumley** [GitGarage/BLEMingleiOS#6]
In particular, the 'split' function has to be used differently in Swift3. This is used in line ~135 of BLEMingle.swift.

**Comment by gitgarage** [comment]
I am going to fix the function that uses split today and will have an update by tonight.

**Comment by will-lumley** [comment]
Thanks @GitGarage, much appreciated! :)
Any update yet?

**Comment by GitGarage** [comment]
Sorry, a work related complication got in the way. I finally finished that project and am ready to get my hands dirty with this.

**Comment by GitGarage** [comment]
Having some trouble replacing the old swift with new swift, but its in progress.

**Comment by gitgarage** [comment]
Got it compiling. I'm guessing it doesn't work since I made a few changes, but I think it will soon be running again.
